/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniTest */

#ifndef _Included_JniTest
#define _Included_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniTest
 * Method:    c_func
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JniTest_c_1func
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
